name: Java CI

on:
  push:

  # trigger when starred
  watch:
    types: [started]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: |
        dotnet tool install gpr -g
        gpr delete ${{ github.repository }}/com.mycompany.app.my-app -k ${{ github.token }}/0.111-SNAPSHOT

    - name: Deploy with Maven
      run: mvn deploy -s settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
