name: Java CI

on:
  push:

  # trigger when starred
  watch:
    types: [started]  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn javadoc:jar
    - run: mvn deploy -Dtoken=${{ secrets.GITHUB_TOKEN }} -s settings.xml -Djavadoc=./target/my-app-1.4-SNAPSHOT-javadoc.jar
