name: Java CI

on:
  push:

  # trigger when starred
  watch:
    types: [started]  

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version: [0.1, 0.1-SNAPSHOT, 0-SNAPSHOT, 0.1.0, 0.1.1, 0.1.0-SNAPSHOT, 0.1.1-SNAPSHOT, 0.1.0-beta, 0.1.1-beta, 0.1.0-beta2, 0.1.1-beta2]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy with Maven
      run: mvn deploy -s settings.xml --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ matrix.version }}
