name: Java CI

on:
  push:

  # trigger when starred
  watch:
    types: [started]  

jobs:
  build:
    env:
      VERSION: "1.${{ github.run_id }}.${{ strategy.job-index }}-test"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Deploy with Maven
      run: mvn deploy -s settings.xml --no-transfer-progress
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ env.VERSION }}
